[package]
name = "paru"
version = "1.2.0"
authors = ["morganamilo <morganamilo@archlinux.org>"]
edition = "2018"

description = "Aur helper and pacman wrapper"
homepage = "http://github.com/Morganamilo/paru"
repository = "http://github.com/Morganamilo/paru"
documentation = "https://docs.rs/paru"
license = "GPL-3.0"
keywords = ["archlinux", "arch", "alpm", "pacman", "aur"]
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md", "help"]


[dependencies]
alpm = "1.1.8"
alpm-utils = "0.6.2"
aur-depends = "0.13.0"
aur-fetch = "0.9.1"
cini = "0.1.1"
pacmanconf = "0.2.0"
raur = "5.0.0"
srcinfo = "1.0.0"


ansi_term = "0.12.1"
anyhow = "1.0.38"
atty = "0.2.14"
chrono = "0.4.19"
dirs = "3.0.1"
futures = "0.3.12"
globset = "0.4.6"
htmlescape = "0.3.1"
indicatif = "0.15.0"
kuchiki = "0.8.1"
nix = "0.19.1"
once_cell = "1.5.2"
reqwest = { version = "0.11.0", features = ["gzip"] }
rss = { version = "1.10.0", default-features = false }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
smart-default = "0.6.0"
tempfile = "3.2.0"
term_size = "0.3.2"
tokio = { version = "1.1.0", features = ["process", "macros", "rt-multi-thread"] }
url = "2.2.0"

[profile.release]
lto = true

[features]
git = ["alpm/git", "alpm-utils/git", "aur-depends/git"]
backtrace = []
generate = ["alpm/generate"]
